### ISSUE TITLE
welcome message comes up on android even if disabled [RELEASE BUILD]

### ISSUE THREAD

**Issue by nikhilvavs** [Instabug/instabug-reactnative#193] opened 2018-08-14 10:55 UTC
React native version: 0.55.1
Instabug Version: 8.0.4
```
if (Platform.OS === 'ios') {
        // ios specific code for instabug
        Instabug.startWithToken(instabugKey, [Instabug.invocationEvent.screenshot]);
        Instabug.setPrimaryColor(processColor(PrimaryColor));
}
if (Platform.OS === 'android') {
        Instabug.enable(); // https://github.com/Instabug/instabug-reactnative/issues/189
}
Instabug.setWelcomeMessageMode(Instabug.welcomeMessageMode.disabled);
BugReporting.setInvocationOptions([Instabug.invocationOptions.invocationOptionsEmailFieldHidden]);
```
On iOS, the behaviour is as expected (i.e. no welcome message is shown), but release build on android, the welcome message still comes up on opening the app.

**Comment by Korazy** [comment] 2018-08-15 08:39
Hey @nikhilvavs 

This is Youssef from the Instabug team. Thanks for pointing this out. We're currently working on a fix for this :)

**Comment by Korazy** [comment] 2018-08-15 11:25
Hey @nikhilvavs 

This is now fixed as of version 8.0.8.

**Closed by Korazy** 2018-08-15 11:25 UTC

**Comment by cayasso** [comment] 2018-08-28 04:03
Hi, I am on Instabug version 8.0.10 and React Native 0.56.0 and I am having the same issue described here on Android, I am unable to disable welcome message and `setWelcomeMessageMode` doesn't seems to work (it works only for iOS). Any quick fix for this?

**Comment by cayasso** [comment] 2018-08-28 04:05
Function that I call in the index constructor:

```js
const setInstabug = () => {
  Instabug.setPrimaryColor(processColor('#2196F3'))
  Instabug.setWelcomeMessageMode(Instabug.welcomeMessageMode.disabled)
  Instabug.startWithToken(config.INSTABUG_TOKEN, [ Instabug.invocationEvent.shake ])

  BugReporting.setShakingThresholdForiPhone(1.5)
  BugReporting.setPromptOptionsEnabled(false, true, true)
  BugReporting.setInvocationOptions([ BugReporting.invocationOptions.commentFieldRequired ])

  const locales = {
    es: Instabug.locale.spanish,
    en: Instabug.locale.english
  }

  Instabug.setLocale(locales[i18n.state.locale])
}
```

**Comment by cayasso** [comment] 2018-08-28 23:32
Any update on this issue, this is really holding me back from pushing my app to Google Play :(

**Comment by Korazy** [comment] 2018-08-28 23:48
Hey @cayasso 

Apologies for the delay. We're looking into this issue as we speak. I will keep you updated with the fix.

**Comment by cayasso** [comment] 2018-08-29 18:44
Can this issue be reopened since it is still an issue? In the mean time I will remove Instabug from my 
Can you also point what was the fix (at least the commit) of this issue in 8.0.8 that you mentioned above.

**Comment by cayasso** [comment] 2018-08-30 03:18
I think I found a way to disable the welcome message in the mean time

```java
@ReactMethod
    public void setWelcomeMessageMode(String welcomeMessageMode) {
        try {
            switch (welcomeMessageMode) {
                case WELCOME_MESSAGE_MODE_LIVE:
                    Instabug.setWelcomeMessageState(WelcomeMessage.State.LIVE);
                    break;
                case WELCOME_MESSAGE_MODE_BETA:
                    Instabug.setWelcomeMessageState(WelcomeMessage.State.BETA);
                    break;
                case WELCOME_MESSAGE_MODE_DISABLED:
                    Instabug.setWelcomeMessageState(WelcomeMessage.State.DISABLED);
                    break;
                default:
                    Instabug.setWelcomeMessageState(WelcomeMessage.State.DISABLED);
            }

        } catch (Exception e) {
            e.printStackTrace();
        }
    }
```

I changed the `default` case to `Instabug.setWelcomeMessageState(WelcomeMessage.State.DISABLED);` instead of `Instabug.setWelcomeMessageState(WelcomeMessage.State.LIVE);` and this seems to be working now for what I need.

**Comment by Korazy** [comment] 2018-08-30 08:28
Prior to version 8.0.8, the methods weren't calling the correct method so they ended up doing nothing which we fixed in that version. We're actually unable to reproduce this issue at all, calling `Instabug.setWelcomeMessageMode(Instabug.welcomeMessageMode.disabled)` disables it on our end. Would you be able to try unlinking and linking again, then trying a clean build?

**Comment by 82rules** [comment] 2018-10-09 18:39
I had the same issue,  my solution was order of operation, disable the message after you start with token
  Instabug.startWithToken(config.INSTABUG_TOKEN, [ Instabug.invocationEvent.shake ])
  Instabug.setWelcomeMessageMode(Instabug.welcomeMessageMode.disabled)

**Comment by Korazy** [comment] 2018-10-10 08:45
@82rules thanks for pointing that out as well :)
