### ISSUE TITLE
The latest version fails because of the bug in the link script.

### ISSUE THREAD

**Issue by jfilter** [Instabug/instabug-reactnative#98] opened 2017-12-04 23:29 UTC
Very easy to reproduce. Just try to link the module.

**Comment by ZiadAyman** [comment] 2017-12-05 08:36
Hey @jfilter 

Do you mind telling me if you were on an older version and this happened while updating? If yes, what version where you on?
Also, were you running npm install and then the link?

**Comment by ZiadAyman** [comment] 2017-12-05 10:25
hey @jfilter never mind we reached the root cause and this should be fixed now.

**Comment by jfilter** [comment] 2017-12-05 10:43
I updated from an older version (2.x.x) to the latest. Then I first unliked it and then it failed to link. I have ruby installed. There was a error in the part where you iterate over the targets. I can look up the specific line number later.

**Closed** 2017-12-05 17:48 UTC

**Comment by ZiadAyman** [comment] 2017-12-06 09:40
@jfilter I expect everything to be in place now. 

Get back please whenever there is anything else we can help you with :)
