### ISSUE TITLE
InvocationOptions enum in JS and iOS code doesn't match

### ISSUE THREAD

**Issue by yongdamsh** [Instabug/instabug-reactnative#180] opened 2018-07-24 06:57 UTC
In JS: 
- https://github.com/Instabug/instabug-reactnative/blob/master/index.js#L1169-L1172
- https://github.com/Instabug/instabug-reactnative/blob/master/modules/BugReporting.js#L218-L221

In iOS:
- https://github.com/Instabug/instabug-reactnative/blob/master/ios/RNInstabug/InstabugReactBridge.m#L628-L631

Because of this issue, adding any `invocationOption` parameter causes an error if the `invokeWithInvocationModeAndOptions` method is called.

**Comment by HeshamMegid** [comment] 2018-07-24 08:12
Thanks for the report. This is due to the same root cause as #179, and we're working on a fix that addresses it.

Closing this for now and keeping the discussion at #179.

**Closed by HeshamMegid** 2018-07-24 08:12 UTC
